name = "ProfileLikelihood"
uuid = "562a7824-9560-45e4-b3f0-1252d152607e"
authors = ["Kevin Phan"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
